### ISSUE TITLE
[BUG] Username must currently match WebAuthnId of user

### ISSUE THREAD

**Issue by mstarongithub** [egregors/passkey#27]
In the current implementation of the registration and login handlers, the username of an account must match the Id used by WebAuthn. This however causes problems with services where the username may change, but the account itself stays the same, or in other words, the username is malleable while the webauthn Id is constant for that account.

The problem itself occurs in the `finishRegistration` and `finishLogin` handlers while attempting to get a user since the webauthn Id is getting used as username

**Comment by egregors** [comment]
I got the point. That sounds reasonable and should be fixed. Thanks! I'll check your PR soon. In this point, I want to think a bit about the new `ifaces` method. Probably it could be a little more explicit, idk yet. Let's discuss it in PR. 

Thank you for your contributing! 🔥 🔥 🔥

**Comment by egregors** [comment]
I just realized, current implementation do not respect difference between `user.id` | `user.name` | `user.displayName`. 
How can I forget about this. This part will be reworked in the first order. Ref: https://www.corbado.com/blog/webauthn-user-id-userhandle#user-name-vs-user-display-name 

`ifaces` will also be changed. User not have to define `user.id`, it should be generated on server side. And it will be like a pk for users collection. `user.name` is some sort of login. User can define it in “traditional” way to auth. And yes, we must have ability to change `user.name` without leak of `user.id` <-> `user.name` relation. And `user.displayName` is just “cosmetic” element, like way how to show username on frontends. 

I'll fix current situation in order to support “traditional” way to auth, but next it will be probably optional way. I believe, usernameless / accountless authentication should be configuration by default. Ref: #30
